steps:
- name: squidfunk/mkdocs-material:3.3.0
  entrypoint: "bash"
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    mkdocs build --strict;
    cp -R site/ /site
  volumes:
  - name: 'site'
    path: '/site'
- name: gcr.io/atomist-web-docs-staging/firebase
  args: ["deploy", "--project=atomist-web-docs-staging", "--only=hosting"]
  volumes:
  - name: 'site'
    path: '/site'

